### ISSUE TITLE
Wrong nginx configuration

### ISSUE THREAD

**Issue by paweljozwicki** [websight-io/starter#102]
**Description**
Using address with <anything>.127.0.0.1.nip.io redirects to the configuration for Bulma page.

**Steps to reproduce**
1. Run local environment
2. Go to http://test.127.0.0.1.nip.io/

**Current result**
Opens a Bulma page

**Expected behavior**
Returns 404

**WebSight CMS version**
1.6.0

**Comment by michalcukierman** [comment]
You can define a `default_server` on port 80.
I am using:
```
# Calls without the domain are probably system health checks.
server {
  listen      80 default_server;
  server_name _;

  location ~ ^(/health|/)$ {
      access_log off;
      add_header  Content-Type    text/html;
      return 200 "Healthy";
  }
}
```

On my project. Note that we need to give non 404 responses for `/` and `/health` requests because it's often used by health checks (and inside of the clusters, the servers are accessed by the IP, not the domain).
