### ISSUE TITLE
"Administration" page has no layout (top bar, left panel, etc)

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#12]
**Description**
"Administration" page has no layout (top bar, left panel, etc)

**WebSight CMS version**
1.0.0

**To Reproduce**
1. Go to 'Resource Browser'
2. Click on 'Administration' in the breadcrumb
3. Administration page is presented. However, it has a different layout.

**Expected behavior**
The layout should be consistent with other pages.

**Screenshots**
![image](https://user-images.githubusercontent.com/106810068/194561880-fabde5aa-e399-4910-ac0d-0203adc5a42c.png)

**Desktop**
 - OS: macOS 
 - Browser: Chrome
 - Version: 105

**Additional context**
- Reported by @pun-ky in https://github.com/websight-io/starter/discussions/11

**Comment by michalcukierman** [comment]
The bug could be introduced by the migration to the newer Atlaskit. 
We should fix it, as the view is inconsistent. The fix should come with the tests ensuring this view is working (as it's not something we verify too often - it's not a core view).

**Comment by paweljozwicki** [comment]
Fixed in CMS version [1.7.0](https://www.websight.io/docs/release-notes/websight-cms/#170-january-18-2023)
