### ISSUE TITLE
docker compose command on linux

### ISSUE THREAD

**Issue by paweljozwicki** [websight-io/starter#127]
docker compose is not a valid command for Linux. 

We should update the documentation or add a script that uses docker-compose.

Possible solution: 
- create the script that checks if `docker compose` or `docker-compose` is available and uses one of them or asks for install.

**Comment by michalcukierman** [comment]
Also, Docker compose is a paid software, therefore it cannot be used in some of organisations. We should update our documentation to say that `Docker Compose` is one of the options.

**Comment by wildone** [comment]
> Also, Docker compose is a paid software, therefore it cannot be used in some of organisations. We should update our documentation to say that `Docker Compose` is one of the options.

You can run docker in ubuntu WSL on windows, same should work on Mac.

Here is my guide on getting around having to run "Docker Desktop" when an enterprise IT does not allow it.
https://aem.design/blog/2022/02/01/goodbye-docker-desktop

**Comment by michalcukierman** [comment]
This is a great article! I agree with it. We should not promote Docker Desktop or at least provide the alternatives.
as for the quickstart script:
```curl https://www.websight.io/scripts/get.sh | sh```

We need to detect the OS and use different command for Linux. Or check if the file executable exists and docker compose is installed)

**Comment by paweljozwicki** [comment]
We simplified the developer environment and we won't use `docker compose` anymore: https://docs.websight.io/cms/quick-start
