### ISSUE TITLE
Creating new page with CapitalsInTitle forces page name

### ISSUE THREAD

**Issue by wildone** [websight-io/starter#133]
Is it possible to lowecase name of a page when its being generated from Title by default?

**Comment by paweljozwicki** [comment]
Yes, we will prepare such an improvement.

**Comment by wildone** [comment]
> Yes, we will prepare such an improvement.

Is the source in github, I can update?

**Comment by paweljozwicki** [comment]
Unfortunately no. At least for now, the source code is not public.

**Comment by paweljozwicki** [comment]
It's resolved in [WebSight CMS version (1.10.0)](https://www.websight.io/docs/release-notes/websight-cms/#1100-march-1-2023)
