### ISSUE TITLE
Clicking system version does not list the system components

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#14]
**Description**
Clicking system version does not list the system components

**WebSight CMS version**
1.0.0

**Steps to Reproduce**
1. Go to 'User Manager'
2. Click on 'System version' in the footer
3. Empty list of components is presented

**Expected behavior**
Information about the system version is presented.

**Screenshots**
![image](https://user-images.githubusercontent.com/106810068/194571240-6a873ab2-9a4a-493d-84de-5f121034d9fe.png)

**Desktop**
 - OS: macOS 
 - Browser: Chrome
 - Version: 105

**Additional context**
- Reported by @pun-ky in https://github.com/websight-io/starter/discussions/11

**Comment by kamil-kwarciak** [comment]
We updated the bug template and the hint on where to find the version of CMS. It is available on the login page. 

BTW. We will unify the layout of admin tools and the footer having System Version will be removed soon.

**Comment by paweljozwicki** [comment]
The layout of admin tools was unified and the footer was removed for Package Manager, User Manager, Groovy Console, and Swagger Browser.

It was changed in [**WebSight CMS version 1.2.0**](https://www.websight.io/docs/release-notes/websight-cms-ce/#120-october-26-2022). 

Once again many thanks to @pun-ky for reporting this issue.
