### ISSUE TITLE
Unable to render resources with wcmmode='disabled', should this work?

### ISSUE THREAD

**Issue by wildone** [websight-io/starter#140]
**Description**
Unable to render resources with wcmmode='disabled', should this work?

**Steps to reproduce**
```
<footer data-sly-resource="${ @ path='footer', resourceType='example/footer', wcmmode='disabled'}"></footer>
```

**Comment by paweljozwicki** [comment]
I think we miss the documentation about that, but in WebSight we have:

- `${wcmmode.isDisabled}`
- `${wcmmode.isEdit}`
- `${wcmmode.isPreview}`

**Comment by wildone** [comment]
also 'org.apache.sling.engine.SlingRequestProcessor' does not seem to be available is there an alternative?

**Comment by paweljozwicki** [comment]
Sorry, I just misunderstood the question. 

Unfortunately, for now, there is no easy way to do this. You would have to set it to `resourceAttributes`, by providing a proper value of `pl.ds.websight.pages.foundation.WcmMode` enum from `pl.ds.websight:websight-pages-foundation-bundle`

After the next release, it will be enabled to be set by
``` 
<footer data-sly-resource="${ @ path='footer', resourceType='example/footer', requestAttributes = wcmmode.disabledModeAttribute}"></footer> 
```

**Comment by wildone** [comment]
ok cool, meanwhile ive made a helper that gets me the resource and i output it using `${model.inheritedHtml @ context='unsafe'}`.

**Comment by paweljozwicki** [comment]
In [WebSight 1.11.0](https://www.websight.io/docs/release-notes/websight-cms/#1110-march-15-2023) you can force wcm mode with:
``` 
<sly data-sly-resource="${'title' @ requestAttributes = wcmmode.disabledModeAttribute}"></sly>
```
More details are available [here](https://www.websight.io/docs/developers/development/wcm-mode/#forcing-wcm-mode-in-htl).
