### ISSUE TITLE
Posting non existent paths to `websight-pages-editor-service.add-component.action` fails.

### ISSUE THREAD

**Issue by wildone** [websight-io/starter#142]
**Description**

I have a component that outputs additional placeholders to paths that do not exist.

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/170312/223094017-123fe9c7-a8bd-4f50-8ddf-a8af2ddbd494.png">

The component resource is `/content/typerefinery-showcase/pages/components/content/text` 

The post action when drop a component into a placeholder is posted here `/content/typerefinery-showcase/pages/components/content/text.websight-pages-editor-service.add-component.action`

with payload 

```
pagePath: 
/content/typerefinery-showcase/pages/components/content/text
componentPath: 
/apps/typerefinery/components/content/image
targetParentPath: 
/content/typerefinery-showcase/pages/components/content/text/jcr:content/rootcontainer/container/section1/text/par1
```

No errors are being dumped, so I assume that because `targetParentPath` does not exist the action fails. Can that action create the path if its not there?

**Comment by paweljozwicki** [comment]
Hi, do I understand correctly that your component is under path `/content/typerefinery-showcase/pages/components/content/text/jcr:content/rootcontainer/container/section1/text/` and the par1 is a resource that not exists? So I assume it's something defined only in HTL?
And you would like to create such a resource while adding a `/apps/typerefinery/components/content/image` component?

**Comment by wildone** [comment]
yes thats correct. Yes the par1 is only in HTL part of the placeholder. And yes ive droped an image onto that placeholder.

**Comment by paweljozwicki** [comment]
Unfortunately, we are working only on resources while adding components, and we don't examine HTL so, it won't be possible. We don't want to extend this step with exploring HTL so the recommended way is to use initial content in such cases. So while you will add a text component you can add a par1 as well. 
To do so, you have to add a `template` to your component with `.content.json`:
```
{
  "jcr:primaryType": "nt:unstructured",
  "par": {
    "jcr:primaryType": "nt:unstructured",
    "sling:resourceType": "resource/type/path"
  }
} 
```
And [there](https://github.com/websight-io/howlite/blob/main/core/src/main/resources/libs/howlite/components/layouts/contentimagefullwidth/template/.content.json) is an example of our usage.

**Comment by wildone** [comment]
Nah its not an inital component issue. Need that action ".websight-pages-editor-service.add-component.action" not to fail.

If I post this payload to it
```
pagePath: 
/content/typerefinery-showcase/pages/components/content/text
componentPath: 
/apps/typerefinery/components/content/image
targetParentPath: 
/content/typerefinery-showcase/pages/components/content/text/jcr:content/rootcontainer/container/section1/text/par1
```

I extect that it will create path `/content/typerefinery-showcase/pages/components/content/text/jcr:content/rootcontainer/container/section1/text/par1` with reference to `/apps/typerefinery/components/content/image` thats all.

Right now my bet there is no error handling on `targetParentPath`. But ill check now.

**Comment by wildone** [comment]
AddComponentRestModel 
```
private void init() {
    this.target = this.resourceResolver.getResource(this.targetParentPath);
    Resource componentResource = this.resourceResolver.getResource(this.componentPath);
    if (componentResource != null)
      this.component = (Component)componentResource.adaptTo(Component.class); 
  }
```

So yeah that `this.target` will be null or `ResourceUtil.isNonExistingResource(this.target)==fasle` so `resourceResolver.create` will fail. Hmm

**Comment by wildone** [comment]
@paweljozwicki ok ive created the action and its registred
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/170312/224048171-63bd2fa2-0235-41da-ad1b-3ae46e0a05ca.png">
but when i post it does not seem to trigger any pointers?

**Comment by wildone** [comment]
Which JS file of top of the head does the post? :)

**Comment by wildone** [comment]
Also if I rename my action from `AddComponentRestAction` to `AddComponent2RestAction` with hope to post to `.websight-pages-editor-service.add-component2.action` does not seem to work.

**Comment by wildone** [comment]
Just as out of interest ive update to this

<img width="252" alt="image" src="https://user-images.githubusercontent.com/170312/224190727-13c3ae99-360e-4227-ac8d-398eb69a47b9.png">

to hope I can run this

```
curl -u wsadmin:wsadmin -X POST -F"pagePath=/content/typerefinery-showcase/pages/components/content/text" -F"componentPath=/apps/typerefinery/components/content/image" -F"targetParentPath=/content/typerefinery-showcase/pages/components/content/text/jcr:content/rootcontainer/container/section1/text/par1" http://localhost:8080/content/typerefinery-showcase/pages/components/content/text.websight-pages-editor-service.update-component.action
```

but nada :(

**Comment by paweljozwicki** [comment]
For sure you should change 
```
curl -u wsadmin:wsadmin -X POST -F"pagePath=/content/typerefinery-showcase/pages/components/content/text" -F"componentPath=/apps/typerefinery/components/content/image" -F"targetParentPath=/content/typerefinery-showcase/pages/components/content/text/jcr:content/rootcontainer/container/section1/text/par1" http://localhost:8080/content/typerefinery-showcase/pages/components/content/text.websight-pages-editor-service.update-component.action
```

to 
```
curl -u wsadmin:wsadmin -X POST -F"pagePath=/content/typerefinery-showcase/pages/components/content/text" -F"componentPath=/apps/typerefinery/components/content/image" -F"targetParentPath=/content/typerefinery-showcase/pages/components/content/text/jcr:content/rootcontainer/container/section1/text/par1" http://localhost:8080/content/typerefinery-showcase/pages/components/content/text.typerefinety-backend.update-component.action
```

(In the previous `.websight-pages-editor-service.add-component2.action` should be `.typerefinety-backend.add-component2.action` )

I will take a look if will be able to find anything else.

**Comment by paweljozwicki** [comment]
And in terms of JS which does the POST it's:

<img width="592" alt="Screenshot 2023-03-10 at 08 54 35" src="https://user-images.githubusercontent.com/109656376/224256731-60252d58-d572-4293-8159-44368a8fa678.png">

**Comment by wildone** [comment]
Yep thanks did find that :D

**Comment by wildone** [comment]
But i might see if I can hijack the selectors :D

**Comment by wildone** [comment]
Is there an official way to override `.websight-pages-editor-service.add-component.action`?

**Comment by wildone** [comment]
Ok ive managed to do this without overriding any servlets!

![textparagraphs](https://user-images.githubusercontent.com/170312/224328606-7a5cfd5f-d6fe-4f6a-a0fc-0b9fd9b0c2f7.gif)

**Comment by wildone** [comment]
here is the docs https://typerefinery.ai/design/textparagraphmode.html
