### ISSUE TITLE
Dropdown and description in the multifield section of the Editor dialog box are not working properly.

### ISSUE THREAD

**Issue by Harikarthyk** [websight-io/starter#149]
**Description**
1. In the multiselect If I use the dropdown, I am not able to select the options from the list.
2. I am not able to view the description when I hover over the description icon in the multifield section.

**Steps to reproduce**
1. Create a drop-down component in a multifield section and add a description to it.
2. Try to select the value in the drop-down list.
3. Hover over the description icon to see if you get the description that is provided.

**Current result**
1. Not able to select any option from the drop-down menu.

**Expected behavior**
On, select the appropriate option from the dropdown menu should be selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/54505967/226265866-d400c454-ace3-4ef4-8ca3-786e223e664b.png)

**WebSight CMS version**
1.10.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version Latest

**Comment by paweljozwicki** [comment]
Resolved in [WebSight CMS 1.11.1](https://www.websight.io/docs/release-notes/websight-cms/#1111-march-21-2023)
