### ISSUE TITLE
Pretty hard to edit the page

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#15]
2 clicks are needed to check the checkbox then click "edit" on top bar
or
move cursor totally to the right and click pencil icon;

 I was suspecting that clicking on the page name will open edit mode; I suggest to maybe provide an option to not be forced to move mouse each time to the right but move this dropdown menu somehow to the left which will eliminate the need from jumping continuosly cursor from left (when navigating between pages) to the right (when wanting to open edit mode / most often operation)

right now it's pretty frustrating (exactly in the same way as on AEM) ;)

what is more, according to my screen resolution, I have enough space to display more action icons than this pencil alone which looks a little bit strange IMO
![image](https://user-images.githubusercontent.com/106810068/194573831-f3643fa3-c5c9-4c5e-b0f7-5a28f712c101.png)

**Additional context**
- Reported by @pun-ky in https://github.com/websight-io/starter/discussions/11

**Comment by paweljozwicki** [comment]
Resolved in [WebSight CMS version (1.10.0)](https://www.websight.io/docs/release-notes/websight-cms/#1100-march-1-2023)
From now on we can open the page editor by clicking on the page name.
