### ISSUE TITLE
Any official way to set X-Frame-Options header?

### ISSUE THREAD

**Issue by wildone** [websight-io/starter#155]
**Is your feature request related to a problem? Please describe.**
I would like to set `X-Frame-Options` header for all responses on CMS so that I can load CMS UI in an iFrame.

**Describe the solution you'd like**
Would like to configure an OSGI config with headers to send with all responses.

**Describe alternatives you've considered**
Running a proxy to do this. :(

**Comment by michalcukierman** [comment]
I guess we need to have a section in the documentation on how to work with the documentation. WDYT @paweljozwicki ?

**Comment by paweljozwicki** [comment]
Totally agree.

**Comment by wildone** [comment]
> I guess we need to have a section in the documentation on how to work with the feature models / configurations. WDYT @paweljozwicki ?

There is sample config in the archetype already, I have been using it.

**Comment by wildone** [comment]
should I keep this open? @paweljozwicki

**Comment by paweljozwicki** [comment]
Yes, let's keep it open until we would prepare the documentation :)
