### ISSUE TITLE
Resource Browser navigation bug.

### ISSUE THREAD

**Issue by wildone** [websight-io/starter#158]
**Description**
Pasting url into the resource address in Resource Browser causes an infinite loop.

**Steps to reproduce**
1. Open resource browser
2. Past url into address

**Expected behavior**
Should just navigate to path is possible and not have to refresh

**Screenshots**
![resourcebrowsernavigationbug](https://user-images.githubusercontent.com/170312/232956366-1d098509-da74-4e90-bde9-448a3a95a40e.gif)

**WebSight CMS version**
1.12.0

**Comment by paweljozwicki** [comment]
Confirmed, thanks for reporting the issue.

**Comment by paweljozwicki** [comment]
Hi, it was fixed in [WebSight CMS version 1.15.0](https://docs.websight.io/cms/release-notes/websight-cms/#1150-may-30-2023).
