### ISSUE TITLE
Footer is not sticky (to the bottom)

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#16]
**Description**
Footer is not sticky (to the bottom)

**WebSight CMS version**
1.0.0

**Steps To Reproduce**
1. Go to 'User Manager'
2. See the footer

**Expected behavior**
The footer should be aligned to the bottom

**Screenshots**
![image](https://user-images.githubusercontent.com/106810068/194574519-d86dba3a-19e1-4957-be69-3666badffb59.png)

**Desktop**
 - OS: macOS 
 - Browser: Chrome
 - Version: 105

**Additional context**
- Reported by @pun-ky in https://github.com/websight-io/starter/discussions/11

**Comment by paweljozwicki** [comment]
The layout of admin tools was unified and the footer was removed for Package Manager, User Manager, Groovy Console, and Swagger Browser.

It was changed in [**WebSight CMS version 1.2.0**](https://www.websight.io/docs/release-notes/websight-cms-ce/#120-october-26-2022). 

Once again many thanks to @pun-ky for reporting this issue.
