### ISSUE TITLE
Can't publish assets on windows.

### ISSUE THREAD

**Issue by wildone** [websight-io/starter#163]
**Description**
When publishing assets the path to asset original image has a colon in it `jcr:content/renditions/original.jpg`. This is invalid on Windows. 

As far as sling is concerned `jcr:content` and `_jcr_content` are interchangeable.

**Steps to reproduce**
1. Add a new asset
2. Publish it
3. Check logs for errors

**Expected behavior**
When publishing an asset published path should have `jcr:content` replaced with `_jcr_content`.

**WebSight CMS version**
1.12.0

**Desktop (please complete the following information):**
 - OS: windows

**Comment by paweljozwicki** [comment]
We are working on a new [publication model](https://github.com/websight-io/roadmap/issues/36) so it shouldn't be a problem in future releases.

**Comment by wildone** [comment]
fixed it.
