### ISSUE TITLE
UX bugs/improvements

### ISSUE THREAD

**Issue by krystian-panek-wttech** [websight-io/starter#179]
**Description**

1. Selecting asset
2. 
Note no background, etc of the panel at the right.

<img width="1504" alt="image" src="https://github.com/websight-io/starter/assets/81212505/244754de-7c43-45a8-a476-6e584663bb1b">

3. Hideable right panel 

It could be nice to work with it on wide screens but on my Mac display, I prefer old-style dialogs only, because now I see the editing options duplicated. I have no clue how to collapse right panel in the same way as I could collapse the left panel using the arrow icon. Probably the same icon to be added for the right panel.

<img width="1508" alt="image" src="https://github.com/websight-io/starter/assets/81212505/65ced5f7-e8e3-4a0a-9d7a-4931f30d6ff1">

**WebSight CMS version**

Fresh setup via install script run today.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: recent

**Comment by michalcukierman** [comment]
Thanks @krystian-panek-wttech we'll create a hotfix for the assets panel as soon as possible. 
For the left-side panel. It's going to be a replacement for dialogs, we find it much more robust (instant previews) and with no extra clicks. It may be not optimal for smaller screens. The hide option could work. We will discuss the possible impact.

On the other side: opening and closing the dialog, or expanding/folding the panel would require as many user actions as clicking "preview" after each change. Anyway, I see the point.

Thanks!

**Comment by kamil-kwarciak** [comment]
@krystian-panek-wttech , we released version 1.20.1. The issue for a selected asset is fixed. 

RE: hiding the properties panel. I moved it to a separate ticket #183
