### ISSUE TITLE
Double-click should open edit dialog

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#18]
Double-click should open edit dialog for a given component

![image](https://user-images.githubusercontent.com/106810068/194576732-52dc3eda-69a5-463b-b461-2e435143f2c9.png)

**Additional context**
- Reported by @pun-ky in https://github.com/websight-io/starter/discussions/11

**Comment by paweljozwicki** [comment]
I forgot to close that one. In [WebSight CMS 1.14.0](https://docs.websight.io/cms/release-notes/#1140-may-10-2023) we introduced double click. By default, it's configured to open the properties dialog but can be changed e.g. to start inline editing.
