### ISSUE TITLE
Image url choose path - no idea how it works

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#19]
**Description**
Image url choose path - no idea how it works. Maybe some picker should be opened somehow but I have no clue how use it

**WebSight CMS version**
1.0.0

**Steps To Reproduce**
1. Edit the homepage for Luna
2. Edit image componnet
3. There is empty URL

**Expected behavior**
I want to understand how to use it

**Screenshots**
![image](https://user-images.githubusercontent.com/106810068/194577618-6cdb3b2d-7505-40b5-a527-4576c7785929.png)

**Desktop**
 - OS: macOS 
 - Browser: Chrome
 - Version: 105

**Additional context**
- Reported by @pun-ky in https://github.com/websight-io/starter/discussions/11

**Comment by michalcukierman** [comment]
Definitely a bad label. I guess it can be a link (internal or external).
References:
- https://github.com/websight-io/howlite/blob/main/core/src/main/resources/libs/howlite/components/image
- https://www.websight.io/docs/authors/component-libs/howlite/image/

We should also have it in the documentation (it's missing now).

**Comment by paweljozwicki** [comment]
Resolved in [WebSight CMS version 1.5.0](https://www.websight.io/docs/release-notes/websight-cms/#150-december-7-2022). Pathpicker placeholder text changed to guide on how to choose a path.
