### ISSUE TITLE
Luna bestsellers too wide

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#21]
**Description**
Luna bestsellers too wide

**WebSight CMS version**
1.0.0

**Steps To Reproduce**
1. Edit the homepage for Luna
2. Scroll to Luna bestsellers

**Expected behavior**
Spacing on the right

**Screenshots**
![image](https://user-images.githubusercontent.com/106810068/194579360-889e32d8-0848-4437-9c19-fea4a1caac80.png)

**Desktop**
 - OS: macOS 
 - Browser: Chrome
 - Version: 105

**Additional context**
- Reported by @pun-ky in https://github.com/websight-io/starter/discussions/11

**Comment by paweljozwicki** [comment]
Additional comment: 
It's not clear that it's a slider. Let's add arrows: 
<img width="333" alt="Screenshot 2022-12-19 at 12 33 33" src="https://user-images.githubusercontent.com/109656376/208417213-740a82e5-ac61-4aba-8b1b-ae8478545d19.png">
On hower background and arrow should invert colors.

**Comment by paweljozwicki** [comment]
Resolved in [1.6.0 version](https://github.com/websight-io/starter/releases/tag/v1.6.0).
