### ISSUE TITLE
Clicking component in the tree should scroll the window to it

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#22]
**Description**
Clicking a component in the tree should scroll the window to it. Now it only highlights it; if in the viewport it is not visible it is needed to scroll it on our own unnecessarily

**WebSight CMS version**
1.0.0

**Steps To Reproduce**
1. Edit the homepage for Luna
2. Click on a component in Content Tree

**Expected behavior**
Window scrolls to the selected component 

**Screenshots**
![image](https://user-images.githubusercontent.com/106810068/194580319-47d843c8-1414-43cc-99a8-bc0b5da96db3.png)

**Desktop**
 - OS: macOS 
 - Browser: Chrome
 - Version: 105

**Additional context**
- Reported by @pun-ky in https://github.com/websight-io/starter/discussions/11

**Comment by paweljozwicki** [comment]
Resolved in [WebSight CMS version 1.4.0](https://www.websight.io/docs/release-notes/websight-cms-ce/#140-november-23-2022).
