### ISSUE TITLE
Browser should be capable to display SVG

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#25]
The browser should be capable to display SVG... why Websight Assets is not trying to display it?

![image](https://user-images.githubusercontent.com/106810068/194582690-a2d94b04-bfad-4fed-a6c8-27de33886e47.png)

**Additional context**

**Comment by michalcukierman** [comment]
we should be using mime-type to identify assets. Each rendition (also original), should have:
```
jcr:mimeType
String
image/svg+xml
```

**Comment by paweljozwicki** [comment]
Fixed in CMS version [1.7.0](https://www.websight.io/docs/release-notes/websight-cms/#170-january-18-2023)
