### ISSUE TITLE
Asset preview dropdown is cut off and has no icons

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#26]
**Description**
Asset preview dropdown is cut off and has no icons

**WebSight CMS version**
1.0.0

**Steps To Reproduce**
1. Go to 'Assets'
2. Open an asset to preview it
3. See the action in the top right corner

**Expected behavior**
The actions presented properly with icons

**Screenshots**
![image](https://user-images.githubusercontent.com/106810068/194582996-f34a1f9e-03f4-4c78-bb6f-68465e2b752b.png)

**Desktop**
 - OS: macOS 
 - Browser: Chrome
 - Version: 105

**Additional context**
- Reported by @pun-ky in https://github.com/websight-io/starter/discussions/11

**Comment by paweljozwicki** [comment]
Solved in [WebSight CMS version 1.3.0](https://www.websight.io/docs/release-notes/websight-cms-ce).

Once again many thanks to @pun-ky for reporting this issue.
