### ISSUE TITLE
Assets browser cuts off image thumbs horizontally

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#33]
**Description**
Assets browser cuts off image thumbs horizontally when panel size is reduced. In general, the thumbnails are resized to some point. Then, they are cut. Further panel size reduction hides it.

**WebSight CMS version**
1.0.0

**Steps To Reproduce**
1. Edit the homepage for Luna
2. Switch the left panel to Assets
3. Narrow the size of the left panel
4. Images are cut but the pannel is still visible

**Expected behavior**
The panel is hidden when further thumbnail size reduction is not possible.

**Screenshots**
![image](https://user-images.githubusercontent.com/106810068/194831924-ec0157fd-5ce1-4e8e-8dc8-3c1d0cc7f2bf.png)

**Desktop**
- OS: macOS
- Browser: Chrome
- Version: 105

**Additional context**
- Reported by @pun-ky in https://github.com/websight-io/starter/discussions/11

**Comment by paweljozwicki** [comment]
Resolved in [WebSight CMS version 1.5.0](https://www.websight.io/docs/release-notes/websight-cms/#150-december-7-2022). The panel is hidden when further thumbnail size reduction is not possible.
