### ISSUE TITLE
Multifield data-test-id is same for all elements based on the label in the dialog

### ISSUE THREAD

**Issue by nowak-pawel-ds** [websight-io/starter#35]
**Is your feature request related to a problem? Please describe.**
When I want to test multiple elements I cannot differenciate them based on data-test-id

<img width="734" alt="obraz" src="https://user-images.githubusercontent.com/110535080/194852761-1725534a-cb75-44b0-823b-fcc7f6448358.png">

**Comment by paweljozwicki** [comment]
Resolved in [WebSight CMS 1.11.1](https://www.websight.io/docs/release-notes/websight-cms/#1111-march-21-2023)
