### ISSUE TITLE
There is no explanation how to hide properties

### ISSUE THREAD

**Issue by nowak-pawel-ds** [websight-io/starter#46]
**Description**
Documentation for container mentions it could be useful for hiding/showing properties but there is no explanation how to do it. 

**Steps to reproduce**
1. Go to (https://www.websight.io/docs/developers/dialogs/container/)

**Expected behavior**
Document how to show hide dialog properties and point it to on container page

**Comment by paweljozwicki** [comment]
Documentation updated: https://www.websight.io/docs/developers/development/dialogs/#conditions
