### ISSUE TITLE
Cannot update WS_ADMIN_PASSWORD

### ISSUE THREAD

**Issue by michalcukierman** [websight-io/starter#48]
**Description**
Setting custom WS_ADMIN_PASSWORD in docker-compose.yml does not work in Luna.

**Steps to reproduce**
1.  Execute `docker system prune`
2.  Execute `docker volume prune`
3. Update `WS_ADMIN_PASSWORD: "wsadminXXX"` in docker-compose.yml
4. Run docker compose up

**Current result**
Credentials are still wsadmin/wsadmin

**Expected behavior**
Credentials are wsadmin/wsadminXXX

**Screenshots**
N/A

**WebSight CMS version**
1.1.0

**Desktop (please complete the following information):**
 - Debian

**Comment by malaskowski** [comment]
Please share `docker-compose.yml` you are using.

**Comment by michalcukierman** [comment]
It's from starter:
https://github.com/websight-io/starter/blob/main/environment/local/docker-compose.yml

password is updated using instructions from README.md

**Comment by michalcukierman** [comment]
Looks like the documentation is outdated:
https://github.com/websight-io/starter/tree/main/environment

plain WS_ADMIN_PASSWORD update is not supported anymore.

**Comment by paweljozwicki** [comment]
That's right, the documentation was outdated.

WS_ADMIN_PASSWORD was removed from Getting Started Guide and from https://github.com/websight-io/starter/tree/main/environment documentation. Instead, there is a section about using [secrets](https://github.com/websight-io/starter/tree/main/environment#secret-files).
