### ISSUE TITLE
Build error - Too many files with unapproved license

### ISSUE THREAD

**Issue by pollenshukla** [websight-io/starter#52]
**Description**
Post setting up the new project, on update of component ran into the Terminal build failure: `"Too many files with unapproved license"` on execution of `./mvnw -f application/backend/pom.xml clean install -P autoInstallBundle`

**Steps to reproduce**
1. Updating the component as per the [official document](https://www.websight.io/docs/developers/quick-start/#component-update)

**Current result**
`[INFO] --- apache-rat-plugin:0.14:check (default) @ luna-backend ---
[INFO] Enabled default license matchers.
[INFO] Will parse SCM ignores for exclusions...
[INFO] Finished adding exclusions from SCM ignore files.
[INFO] 62 implicit excludes.
[INFO] 6 explicit excludes.
[INFO] 7 resources included
[INFO] Rat check: Summary over all files. Unapproved: 2, unknown: 2, generated: 0, approved: 5 licenses.
[INFO] Enabled default license matchers.
[INFO] Will parse SCM ignores for exclusions...
[INFO] Finished adding exclusions from SCM ignore files.
[INFO] 62 implicit excludes.
[INFO] 6 explicit excludes.
[INFO] 7 resources included
[WARNING] Files with unapproved licenses:
  /Users/pollen/Developer/websight/starter/application/backend/src/test/test.iml
  /Users/pollen/Developer/websight/starter/application/backend/src/main/main.iml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.617 s
[INFO] Finished at: 2022-10-22T14:32:46-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.14:check (default) on project luna-backend: Too many files with unapproved license: 2 See RAT report in: /Users/pollen/Developer/websight/starter/application/backend/target/rat.txt -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Expected behavior**

**Screenshots**

**WebSight CMS version**
A version of CMS you are using (you will find it on the login page).

**Desktop (please complete the following information):**
 - OS: Mac iOS
 - Device: MacBook Pro M1

**Comment by michalcukierman** [comment]
@pollenshukla We use RAT (Release Audit Tool) for our open-source projects to ensure we have licenses on every file.
This check should be disabled for changes not meant to be a part of Howlite release. 

You could run a project with a disabled RAT plugin (with `-Drat.skip=true` flag) as a workaround.

The full command will be:
`./mvnw -f application/backend/pom.xml clean install -Drat.skip=true -P autoInstallBundle`

Alternatively, you can disable it permanently  by adding additional plugin configuration to your pom.xml:
```
<plugin>
    <groupId>org.apache.rat</groupId>
    <artifactId>apache-rat-plugin</artifactId>

    <configuration>
        <skip>true</skip>
    </configuration>
</plugin>
```

or simply remove the whole plugin from here (it's were it's configured):
https://github.com/websight-io/howlite/blob/main/pom.xml#L130

**Comment by michalcukierman** [comment]
The correct pom.xml file with RAT plugin configuration for `starter` is:
https://github.com/websight-io/starter/blob/main/pom.xml#L101

**Comment by michalcukierman** [comment]
@pollenshukla You can pull the latest changes - I've removed the plugin for now. Will add it again when we find a way to use it without affecting end users.

**Comment by pollenshukla** [comment]
Thanks @michalcukierman for a quick resolution, otherwise you can update as a note in documentation.
