### ISSUE TITLE
Change formatting for WebSight Technologies documentation

### ISSUE THREAD

**Issue by paweljozwicki** [websight-io/starter#62]
**Description**
We have [documentation with technologies used to design, build and launch WebSight](https://github.com/websight-io/starter#websight-technologies). 
Prepare some other formatting for this section to be more readable.
Additionally, it's bearly visible in dark mode.

**Expected behavior**
Better design of WebSight technologies section, good looking also in dark mode.

**Screenshots**

<img width="862" alt="WebSight technologies in dark mode" src="https://user-images.githubusercontent.com/109656376/202179526-3ad49b96-0633-4fe7-9d54-015a8ba6a932.png">

**Comment by martyna-ds** [comment]
Corrected
