### ISSUE TITLE
Disabled radio component inside multifield

### ISSUE THREAD

**Issue by gfazek** [websight-io/starter#63]
**Description**
I tried to integrate the icon component into the breadcrumb element's multifield (https://github.com/websight-io/bulma/issues/81), but the radio componet is greyed out, and the logic gets broken. The same integration works outside of the multifield, so it seems the problem is with multifield.

**Current result**
It blocks integrating radio components (maybe other type of fields too) into multifield

**Expected behavior**
Components such as radio are functioning properly inside multifield

**Screenshots**
See select it / type it radio component greyed out and disabled
![image](https://user-images.githubusercontent.com/23404209/203067025-4cb5d57e-38e8-4397-888a-85c63f747e20.png)
**WebSight CMS version**
1.2.0

**Comment by paweljozwicki** [comment]
Thanks for creating an issue. It's confirmed also on WebSight CMS version 1.3.0 with a checkbox dialog field.
