### ISSUE TITLE
Are you able to convert this to maven archetype?

### ISSUE THREAD

**Issue by wildone** [websight-io/starter#74]
This will allow easy generation for new projects.

**Comment by paweljozwicki** [comment]
We already have an archetype that allows creating a project with the same structure as in this project. [Here](https://www.websight.io/docs/developers/setup/#generate-a-project) you can read more about that.

**Comment by wildone** [comment]
Thanks my bad, saw the docs after I posted came to close this. Sorry.

Is there a repo for archetype to ask some questions? As distribution throws errors after I run `mvn install`. This is from clean archetype generate.

```
Execution build-docker-image of goal io.fabric8:docker-maven-plugin:0.40.1:build failed: An API incompatibility was encountered while executing io.fabric8:docker-maven-plugin:0.40.1:build: java.lang.UnsatisfiedLinkError: The specified procedure could not be found.
```

This is a command that I used on windows.

```
mvn archetype:generate -DarchetypeGroupId="pl.ds.websight" -DarchetypeArtifactId="websight-cms-ce-project-archetype" -DarchetypeVersion="1.4" -DgroupId="io.typerefinery.websight" -DartifactId="typerefinery" -Dversion="1.0.0-SNAPSHOT" -DprojectName="Typerefinery CMS Project" -DprojectId="typerefinery" -Dpackage="io.typerefinery.websight" -DcmsVersion="1.4.0"
```

**Comment by paweljozwicki** [comment]
Not a problem. 

Here is the best place to ask questions and add issues related to WebSight CMS.
But just to not mix topics, let's close this one and open a new issue, please.
