### ISSUE TITLE
Using vh style breaks Page Editor

### ISSUE THREAD

**Issue by paweljozwicki** [websight-io/starter#96]
**Description**
Using vh style breaks Page Editor

**Steps to reproduce**
1. Use a style with vh e.g. "height: 100vh" in any component
2. Add this component to a page
3. The page in Page Editor in both Edit and Preview modes will extend its size constantly.

**Current result**
Describe the result caused by the bug.

**Expected behavior**
Style based on vh won't break the page view in Page Editor.

**WebSight CMS version**
1.5.0

**Comment by michalcukierman** [comment]
@paweljozwicki I guess this one can be closed as it's fixed in WebSight 1.7.0 ?
