### ISSUE TITLE
No responsiveness in preview mode under 990px

### ISSUE THREAD

**Issue by martyna-ds** [websight-io/starter#98]
**Description**
When in preview mode, can't shrink the page to see actual mobile/tablet version (stops at 990px).

**Steps to reproduce**
1. Select page to edit
2. Click on 'Preview'
3. Try to shrink the page manually with browser window or console under 990px

**Current result**
Page is displaying like in 990px, only half of content is visible

**Expected behavior**
Page should be shrinking accordingly to browser window, like published page 

**WebSight CMS version**
Version: 1.6.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 108.0.5359.124

**Comment by paweljozwicki** [comment]
It's confirmed and queued to be improved in CMS.

**Comment by kamil-kwarciak** [comment]
We added an option to see a page as published (before its publication)  in version 1.20.0. Please use this view to check other viewports.
